# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f5f5187223b97b835f5cf80c5b3989cc3ec6b491ee0d144ac3627ab8e5c2c8923663a6be689b69f3b29a4e66a437b48cf61dd5f3f682f4761456280e50ba96

test:
  secret_key_base: fe780073426e606cb7a2864540afe7f3fb45451e21c424134cb2ffe976339800dcbd591424832a17529a3fa6a0cbc11afc597f632fb14cb052b467b83d81b9c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
